modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="natureandmyths"
version="1.0.1"
displayName="Nature and Myths"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="NightEagle2426"

[[dependencies.natureandmyths]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



